"""empty message

Revision ID: 7ec82d66cf93
Revises: 788be6f3669a
Create Date: 2025-07-28 10:53:44.694496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec82d66cf93'
down_revision = '788be6f3669a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_from_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('follower_user_origin_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_from_id'], ['id'])
        batch_op.drop_column('user_origin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_origin_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('follower_user_origin_id_fkey', 'user', ['user_origin_id'], ['id'])
        batch_op.drop_column('user_from_id')

    # ### end Alembic commands ###
